#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "OceanicNext"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    vim_help_language = "cn"
    bootstrap_before = "myspacevim#before"

# For Theme oceanic-next
[[layers]]
  name = "colorscheme"
[[custom_plugins]]
  name = "vim-airline/vim-airline-themes"
[[custom_plugins]]
  repo = "mhartington/oceanic-next"
  merged = 0


# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "chinese"

[[custom_plugins]]
  name = 'wakatime/vim-wakatime'

  # 以悬浮窗口的形式打开终端
[[custom_plugins]]
  name = 'voldikss/vim-floaterm'

# 更加美观的 tagbar
[[custom_plugins]]
  name = 'liuchengxu/vista.vim'
